# Reading Data
Create a SQL database connection to a sample SQL database, and read records from that database
- Pandas.read_sql
- SQLite3

In [ ]:
# import libraries, pandas, sqlite3
# connect to database
# write query - check all existing table names first
# improve query

In [2]:
import pandas as pd
import sqlite3 as sq3

In [3]:
path = 'data/superheroes.db'
connection = sq3.Connection(path)

In [6]:
query = """
SELECT *
FROM sqlite_master WHERE type = "table";
"""
tables = pd.read_sql_query(query,connection)
tables

,type,name,tbl_name,rootpage,sql
0,table,superheroes,superheroes,2,"CREATE TABLE ""superheroes"" (id integer primary..."
1,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"

In [10]:
query = """
SELECT *
FROM superheroes;
"""
df = pd.read_sql_query(query,connection)
df

,id,name,eye_color,hair_color,appearance_count,first_appearance,first_appearance_year
0,1,Batman (Bruce Wayne),Blue Eyes,Black Hair,3093.0,"1939, May",1939
1,2,Superman (Clark Kent),Blue Eyes,Black Hair,2496.0,"1986, October",1986
2,3,Green Lantern (Hal Jordan),Brown Eyes,Brown Hair,1565.0,"1959, October",1959
3,4,James Gordon (New Earth),Brown Eyes,White Hair,1316.0,"1987, February",1987
4,5,Richard Grayson (New Earth),Blue Eyes,Black Hair,1237.0,"1940, April",1940
...,...,...,...,...,...,...,...
6890,6891,James Garfield (New Earth),None,None,NaN,None,None
6891,6892,Nadine West (New Earth),None,None,NaN,None,None
6892,6893,Warren Harding (New Earth),None,None,NaN,None,None
6893,6894,William Harrison (New Earth),None,None,NaN,None,None
6894,6895,William McKinley (New Earth),None,None,NaN,None,None

In [ ]:
path = 'data/superheroes.db'
conn = sq3.Connection(path)

In [ ]:
query = """
SELECT * 
FROM sqlite_master WHERE type = 'table'
"""
tables = pd.read_sql_query(query, conn)
tables

In [ ]:
query = """
SELECT *
FROM superheroes;
"""
data = pd.read_sql(query, conn)
data

In [ ]:
query = """
SELECT *
FROM superheroes
WHERE appearance_count IS NOT NULL
AND first_appearance IS NOT NULL
AND eye_color IS NOT NULL
ORDER BY appearance_count desc
"""
data = pd.read_sql(query, conn)
data